# ì´ìŠˆ í…œí”Œë¦¿ ì„¤ì •
# ê°™ì€ ë””ë ‰í† ë¦¬ì˜ .md íŒŒì¼ì´ New Issue ì‹œ ì„ íƒ ëª©ë¡ì— ìë™ìœ¼ë¡œ í‘œì‹œë©ë‹ˆë‹¤.
#
# ì‚¬ìš© ì¤‘ì¸ í…œí”Œë¦¿:
#   - feat_template.md   (ê¸°ëŠ¥ ê°œë°œ)
#   - fix_template.md    (ë²„ê·¸ ìˆ˜ì •)
#   - docs_template.md   (ë¬¸ì„œ ê°œì„ )
#   - refactor_template.md (ë¦¬íŒ©í„°ë§)
#   - chore_template.md  (ê¸°íƒ€ ì‘ì—…)

blank_issues_enabled: false

contact_links:
  - name: ğŸ“ ì»¤ë°‹ ì»¨ë²¤ì…˜
    url: https://github.com/GDG-on-Campus-KNU/winter-sprint-5.5st-team1-be/blob/main/.github/commit_convention.md
    about: ì»¤ë°‹ ë©”ì‹œì§€ ì‘ì„± ê·œì¹™ì„ í™•ì¸í•˜ì„¸ìš”
